// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDockerVersion: () => typedError<string, AppError>(__TAURI_INVOKE("get_docker_version")),
	listContainers: () => typedError<ContainerSummary[], AppError>(__TAURI_INVOKE("list_containers")),
	toggleService: (service: ServiceId) => typedError<null, AppError>(__TAURI_INVOKE("toggle_service", { service })),
	getServicesStatus: () => typedError<Partial<{ [key in ServiceId]: ServiceStatus }>, AppError>(__TAURI_INVOKE("get_services_status")),
	getServiceConfigs: () => typedError<Partial<{ [key in ServiceId]: ServiceConfig }>, AppError>(__TAURI_INVOKE("get_service_configs")),
	setServiceConfig: (service: ServiceId, config: ServiceConfig) => typedError<boolean, AppError>(__TAURI_INVOKE("set_service_config", { service, config })),
	globalOn: () => typedError<null, AppError>(__TAURI_INVOKE("global_on")),
	globalOff: () => typedError<null, AppError>(__TAURI_INVOKE("global_off")),
	pickProjectFolder: () => typedError<string | null, AppError>(__TAURI_INVOKE("pick_project_folder")),
	registerProject: (name: string, path: string) => typedError<ProjectConfig, AppError>(__TAURI_INVOKE("register_project", { name, path })),
	importProject: (path: string) => typedError<ImportResult, AppError>(__TAURI_INVOKE("import_project", { path })),
	listProjects: () => typedError<ProjectConfig[], AppError>(__TAURI_INVOKE("list_projects")),
	getComposeDriver: () => typedError<ComposeDriver, AppError>(__TAURI_INVOKE("get_compose_driver")),
	/**  Return the full artisan command catalog. */
	listArtisanCommands: () => typedError<ArtisanCommand[], AppError>(__TAURI_INVOKE("list_artisan_commands")),
	/**
	 *  Stream artisan/shell output to the frontend via Channel<CommandChunk>.
	 * 
	 *  Auto-detects the running app container via Docker Compose labels (project folder name).
	 *  Stores a CancellationToken in ProjectsState keyed by project_id for cancellation.
	 */
	runArtisanCommand: (commandId: string, projectId: string, onChunk: Channel<CommandChunk>) => typedError<null, AppError>(__TAURI_INVOKE("run_artisan_command", { commandId, projectId, onChunk })),
	/**  Cancel a running artisan command for the given project. */
	cancelArtisanCommand: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_artisan_command", { projectId })),
	scaffoldProject: (template: ScaffoldTemplate, projectName: string, parentDir: string, onChunk: Channel<ScaffoldChunk>) => typedError<null, AppError>(__TAURI_INVOKE("scaffold_project", { template, projectName, parentDir, onChunk })),
	/**
	 *  Start streaming logs for a project: docker container stdout/stderr + laravel.log file tail.
	 * 
	 *  Auto-detects the running app container via Docker Compose labels (project folder name).
	 *  File tail runs even when no container is running — docker stream is optional.
	 *  Both streams share a single CancellationToken keyed "logs:{project_id}" in ProjectsState.
	 *  Call stop_log_stream to cancel all streams for this project.
	 */
	startLogStream: (projectId: string, projectPath: string, onLine: Channel<LogLine>) => typedError<null, AppError>(__TAURI_INVOKE("start_log_stream", { projectId, projectPath, onLine })),
	/**  Cancel all log streams for the given project. */
	stopLogStream: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("stop_log_stream", { projectId })),
	readEnvFile: (projectId: string) => typedError<EnvReadResult, AppError>(__TAURI_INVOKE("read_env_file", { projectId })),
	saveEnvFile: (projectId: string, entries: EnvEntry[]) => typedError<null, AppError>(__TAURI_INVOKE("save_env_file", { projectId, entries })),
	toggleViteAuto: (projectId: string, viteAuto: boolean) => typedError<ProjectConfig, AppError>(__TAURI_INVOKE("toggle_vite_auto", { projectId, viteAuto })),
	generateXdebugConfig: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("generate_xdebug_config", { projectId })),
	readPhpIni: (projectId: string) => typedError<IniSection[], AppError>(__TAURI_INVOKE("read_php_ini", { projectId })),
	savePhpIni: (projectId: string, sections: IniSection[]) => typedError<null, AppError>(__TAURI_INVOKE("save_php_ini", { projectId, sections })),
	listSupervisorWorkers: (supervisorContainer: string) => typedError<SupervisorWorker[], AppError>(__TAURI_INVOKE("list_supervisor_workers", { supervisorContainer })),
	restartSupervisorWorker: (supervisorContainer: string, workerName: string) => typedError<null, AppError>(__TAURI_INVOKE("restart_supervisor_worker", { supervisorContainer, workerName })),
	openProjectFolder: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("open_project_folder", { projectId })),
	/**
	 *  Start project containers. Auto-detects Sail, Compose Plugin, or Legacy.
	 *  If `up -d` fails due to a healthcheck dependency (e.g. meilisearch exits before
	 *  laravel.test starts), retries with `--no-deps` on the app service so the Laravel
	 *  container comes up even when optional services are unhealthy.
	 */
	startProject: (projectId: string) => typedError<string, AppError>(__TAURI_INVOKE("start_project", { projectId })),
	/**  Stop project containers. Auto-detects Sail, Compose Plugin, or Legacy. */
	stopProject: (projectId: string) => typedError<string, AppError>(__TAURI_INVOKE("stop_project", { projectId })),
};

/* Types */
export type AppError = { kind: "DockerUnavailable"; message: string } | { kind: "DockerApi"; message: string } | { kind: "DockerPermission"; message: string } | { kind: "ContainerNotFound"; message: string } | { kind: "Internal"; message: string } | { kind: "NotFound"; message: string };

export type ArtisanCommand = {
	id: string,
	label: string,
	kind: CommandKind,
	destructive: boolean,
};

export type CommandChunk = {
	text: string,
	is_stderr: boolean,
};

export type CommandKind = 
/**  php artisan {args} inside app container */
({ Artisan: string }) & { ShellInContainer?: never } | 
/**  Raw shell command inside app container */
({ ShellInContainer: string }) & { Artisan?: never };

export type ComposeDriver = "Plugin" | "Legacy" | "None";

/**  Typed summary of a container — specta-exportable (no serde_json::Value) */
export type ContainerSummary = {
	id: string,
	names: string[],
	image: string,
	status: string,
	state: string,
};

export type EnvEntry = {
	key: string,
	value: string,
	is_comment: boolean,
};

export type EnvFile = {
	entries: EnvEntry[],
};

export type EnvReadResult = {
	env: EnvFile,
	example: EnvFile,
};

export type ImportResult = {
	path: string,
	detected_files: string[],
};

export type IniEntry = {
	key: string,
	value: string,
	is_comment: boolean,
};

export type IniSection = {
	name: string,
	entries: IniEntry[],
};

export type LogLine = {
	text: string,
	source: LogSource,
	timestamp: string | null,
};

export type LogSource = "Docker" | "Laravel" | "Nginx" | "Supervisor";

export type ProjectConfig = {
	id: string,
	name: string,
	path: string,
	vite_auto: boolean,
};

export type ScaffoldChunk = {
	text: string,
	done: boolean,
	error: boolean,
};

export type ScaffoldTemplate = "Tall" | "InertiaVue3" | "InertiaReact";

export type ServiceConfig = {
	image_tag: string,
	port: number,
};

export type ServiceId = "redis" | "postgres" | "mailpit";

export type ServiceStatus = { kind: "stopped" } | { kind: "starting" } | { kind: "running" } | { kind: "stopping" } | { kind: "unhealthy" } | { kind: "error"; message: string };

export type SupervisorWorker = {
	name: string,
	status: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

