// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getDockerVersion: () => typedError<string, AppError>(__TAURI_INVOKE("get_docker_version")),
	listContainers: () => typedError<ContainerSummary[], AppError>(__TAURI_INVOKE("list_containers")),
	toggleService: (service: ServiceId) => typedError<null, AppError>(__TAURI_INVOKE("toggle_service", { service })),
	getServicesStatus: () => typedError<Partial<{ [key in ServiceId]: ServiceStatus }>, AppError>(__TAURI_INVOKE("get_services_status")),
	setServiceConfig: (service: ServiceId, config: ServiceConfig) => typedError<boolean, AppError>(__TAURI_INVOKE("set_service_config", { service, config })),
	globalOn: () => typedError<null, AppError>(__TAURI_INVOKE("global_on")),
	globalOff: () => typedError<null, AppError>(__TAURI_INVOKE("global_off")),
};

/* Types */
export type AppError = { kind: "DockerUnavailable"; message: string } | { kind: "DockerApi"; message: string } | { kind: "DockerPermission"; message: string } | { kind: "ContainerNotFound"; message: string } | { kind: "Internal"; message: string };

/**  Typed summary of a container — specta-exportable (no serde_json::Value) */
export type ContainerSummary = {
	id: string,
	names: string[],
	image: string,
	status: string,
	state: string,
};

export type ServiceConfig = {
	image_tag: string,
	port: number,
};

export type ServiceId = "redis" | "postgres" | "mailpit";

export type ServiceStatus = { kind: "stopped" } | { kind: "starting" } | { kind: "running" } | { kind: "stopping" } | { kind: "error"; message: string };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

