// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getDockerVersion: () => typedError<string, AppError>(__TAURI_INVOKE("get_docker_version")),
	listContainers: () => typedError<ContainerSummary[], AppError>(__TAURI_INVOKE("list_containers")),
	toggleService: (service: ServiceId) => typedError<null, AppError>(__TAURI_INVOKE("toggle_service", { service })),
	getServicesStatus: () => typedError<Partial<{ [key in ServiceId]: ServiceStatus }>, AppError>(__TAURI_INVOKE("get_services_status")),
	getServiceConfigs: () => typedError<Partial<{ [key in ServiceId]: ServiceConfig }>, AppError>(__TAURI_INVOKE("get_service_configs")),
	setServiceConfig: (service: ServiceId, config: ServiceConfig) => typedError<boolean, AppError>(__TAURI_INVOKE("set_service_config", { service, config })),
	globalOn: () => typedError<null, AppError>(__TAURI_INVOKE("global_on")),
	globalOff: () => typedError<null, AppError>(__TAURI_INVOKE("global_off")),
	pickProjectFolder: () => typedError<string | null, AppError>(__TAURI_INVOKE("pick_project_folder")),
	registerProject: (name: string, path: string) => typedError<ProjectConfig, AppError>(__TAURI_INVOKE("register_project", { name, path })),
	importProject: (path: string) => typedError<ImportResult, AppError>(__TAURI_INVOKE("import_project", { path })),
	listProjects: () => typedError<ProjectConfig[], AppError>(__TAURI_INVOKE("list_projects")),
	getComposeDriver: () => typedError<ComposeDriver, AppError>(__TAURI_INVOKE("get_compose_driver")),
	/**  Return the full artisan command catalog. */
	listArtisanCommands: () => typedError<ArtisanCommand[], AppError>(__TAURI_INVOKE("list_artisan_commands")),
	/**
	 *  Stream artisan/shell output to the frontend via Channel<CommandChunk>.
	 * 
	 *  Auto-detects the running app container via Docker Compose labels (project folder name).
	 *  Stores a CancellationToken in ProjectsState keyed by project_id for cancellation.
	 */
	runArtisanCommand: (commandId: string, projectId: string, onChunk: Channel<CommandChunk>) => typedError<null, AppError>(__TAURI_INVOKE("run_artisan_command", { commandId, projectId, onChunk })),
	/**  Cancel a running artisan command for the given project. */
	cancelArtisanCommand: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("cancel_artisan_command", { projectId })),
	scaffoldProject: (template: ScaffoldTemplate, projectName: string, parentDir: string, onChunk: Channel<ScaffoldChunk>) => typedError<null, AppError>(__TAURI_INVOKE("scaffold_project", { template, projectName, parentDir, onChunk })),
	/**
	 *  Start streaming logs for a project: docker container stdout/stderr + laravel.log file tail.
	 * 
	 *  Auto-detects the running app container via Docker Compose labels (project folder name).
	 *  File tail runs even when no container is running — docker stream is optional.
	 *  Both streams share a single CancellationToken keyed "logs:{project_id}" in ProjectsState.
	 *  Call stop_log_stream to cancel all streams for this project.
	 */
	startLogStream: (projectId: string, projectPath: string, onLine: Channel<LogLine>) => typedError<null, AppError>(__TAURI_INVOKE("start_log_stream", { projectId, projectPath, onLine })),
	/**  Cancel all log streams for the given project. */
	stopLogStream: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("stop_log_stream", { projectId })),
	readEnvFile: (projectId: string) => typedError<EnvReadResult, AppError>(__TAURI_INVOKE("read_env_file", { projectId })),
	saveEnvFile: (projectId: string, entries: EnvEntry[]) => typedError<null, AppError>(__TAURI_INVOKE("save_env_file", { projectId, entries })),
	toggleViteAuto: (projectId: string, viteAuto: boolean) => typedError<ProjectConfig, AppError>(__TAURI_INVOKE("toggle_vite_auto", { projectId, viteAuto })),
	generateXdebugConfig: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("generate_xdebug_config", { projectId })),
	readPhpIni: (projectId: string) => typedError<IniSection[], AppError>(__TAURI_INVOKE("read_php_ini", { projectId })),
	savePhpIni: (projectId: string, sections: IniSection[]) => typedError<null, AppError>(__TAURI_INVOKE("save_php_ini", { projectId, sections })),
	listSupervisorWorkers: (supervisorContainer: string) => typedError<SupervisorWorker[], AppError>(__TAURI_INVOKE("list_supervisor_workers", { supervisorContainer })),
	restartSupervisorWorker: (supervisorContainer: string, workerName: string) => typedError<null, AppError>(__TAURI_INVOKE("restart_supervisor_worker", { supervisorContainer, workerName })),
	openProjectFolder: (projectId: string) => typedError<null, AppError>(__TAURI_INVOKE("open_project_folder", { projectId })),
	/**
	 *  Start project containers — strict 2-stage recovery.
	 * 
	 *  Stage 1 — full `up -d` + readiness poll (30 s): waits until ALL containers
	 *             are running+healthy. Returns Ok only when all pass.
	 *  Stage 2 — Docker restart loop: restarts exited/unhealthy containers, re-runs
	 *             `up -d`, polls again (25 s). Returns Ok only when all pass.
	 * 
	 *  On success, spawns a 5 s health monitor that emits `project://status` events.
	 *  On failure, returns the names of the services that did not reach healthy state.
	 */
	startProject: (projectId: string) => typedError<string, AppError>(__TAURI_INVOKE("start_project", { projectId })),
	/**  Stop project containers. Aborts health monitor, runs compose down, emits final Stopped event. */
	stopProject: (projectId: string) => typedError<string, AppError>(__TAURI_INVOKE("stop_project", { projectId })),
	/**  Return current `ProjectStatus` for a project by querying Docker. */
	getProjectStatus: (projectId: string) => typedError<ProjectStatus, AppError>(__TAURI_INVOKE("get_project_status", { projectId })),
	readComposeFile: (projectId: string) => typedError<string, AppError>(__TAURI_INVOKE("read_compose_file", { projectId })),
	saveComposeFile: (projectId: string, content: string) => typedError<null, AppError>(__TAURI_INVOKE("save_compose_file", { projectId, content })),
	/** Return unified diff between last two committed versions of docker-compose.yml. Empty string when fewer than 2 commits. */
	getComposeDiff: (projectId: string) => typedError<string, AppError>(__TAURI_INVOKE("get_compose_diff", { projectId })),
	getSettings: () => typedError<AppSettingsData, AppError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (newData: AppSettingsData) => typedError<null, AppError>(__TAURI_INVOKE("save_settings", { newData })),
	/**  Tauri command wrapper for create_testing_db_inner. */
	createTestingDb: (projectName: string) => typedError<null, AppError>(__TAURI_INVOKE("create_testing_db", { projectName })),
	/**  Dump project database via pg_dump to a user-chosen file path via native save dialog. */
	dumpDb: (projectName: string) => typedError<null, AppError>(__TAURI_INVOKE("dump_db", { projectName })),
	/**  Restore project database from a user-chosen file path via native open dialog. */
	restoreDb: (projectName: string) => typedError<null, AppError>(__TAURI_INVOKE("restore_db", { projectName })),
	/**
	 *  Open an interactive psql CLI session in the global postgres container.
	 *
	 *  Streams output via the existing docker_exec_stream adapter.
	 */
	openDbCli: (projectName: string, onChunk: Channel<CommandChunk>) => typedError<null, AppError>(__TAURI_INVOKE("open_db_cli", { projectName, onChunk })),
	/** List all Docker volumes with name, driver, mountpoint, and size in MB. */
	listVolumes: () => typedError<VolumeInfo[], AppError>(__TAURI_INVOKE("list_volumes")),
	/** Prune dangling (unused) volumes. Returns reclaimed space in bytes. */
	pruneVolumes: () => typedError<number, AppError>(__TAURI_INVOKE("prune_volumes")),
	/** List all local Docker images with tags and size. */
	listImages: () => typedError<ImageInfo[], AppError>(__TAURI_INVOKE("list_images")),
	/** Pull a Docker image by name and tag. Drains the stream fully before returning. */
	pullImage: (image: string, tag: string) => typedError<null, AppError>(__TAURI_INVOKE("pull_image", { image, tag })),
	/** Remove a Docker image by ID. */
	removeImage: (imageId: string) => typedError<null, AppError>(__TAURI_INVOKE("remove_image", { imageId })),
	/** Prune dangling (unused) images. Returns reclaimed space in bytes. */
	pruneImages: () => typedError<number, AppError>(__TAURI_INVOKE("prune_images")),
	/** Fetch template manifest from GitHub raw URL. Done in Rust to avoid CSP issues. */
	fetchTemplateManifest: () => typedError<TemplateEntry[], AppError>(__TAURI_INVOKE("fetch_template_manifest")),
	/** Download a template's docker-compose.yml to a user-chosen directory. */
	installTemplate: (composeUrl: string) => typedError<string, AppError>(__TAURI_INVOKE("install_template", { composeUrl })),
};

/** Events */
export const events = {
	projectStatusEvent: makeEvent<ProjectStatusEvent>("project-status-event"),
};

/* Types */
export type AppError = { kind: "DockerUnavailable"; message: string } | { kind: "DockerApi"; message: string } | { kind: "DockerPermission"; message: string } | { kind: "ContainerNotFound"; message: string } | { kind: "Internal"; message: string } | { kind: "NotFound"; message: string };

/**  Application settings — persisted via tauri-plugin-store. */
export type AppSettingsData = {
	theme: string,
	locale: string,
	tray_enabled: boolean,
	autostart_enabled: boolean,
	docker_socket: string | null,
};

export type ArtisanCommand = {
	id: string,
	label: string,
	kind: CommandKind,
	destructive: boolean,
};

export type CommandChunk = {
	text: string,
	is_stderr: boolean,
};

export type CommandKind = 
/**  php artisan {args} inside app container */
({ Artisan: string }) & { ShellInContainer?: never } | 
/**  Raw shell command inside app container */
({ ShellInContainer: string }) & { Artisan?: never };

export type ComposeDriver = "Plugin" | "Legacy" | "None";

/**  Typed summary of a container — specta-exportable (no serde_json::Value) */
export type ContainerSummary = {
	id: string,
	names: string[],
	image: string,
	status: string,
	state: string,
};

export type EnvEntry = {
	key: string,
	value: string,
	is_comment: boolean,
};

export type EnvFile = {
	entries: EnvEntry[],
};

export type EnvReadResult = {
	env: EnvFile,
	example: EnvFile,
};

export type ImageInfo = {
	id: string,
	tags: string[],
	size: number,
};

export type ImportResult = {
	path: string,
	detected_files: string[],
};

export type IniEntry = {
	key: string,
	value: string,
	is_comment: boolean,
};

export type IniSection = {
	name: string,
	entries: IniEntry[],
};

export type LogLine = {
	text: string,
	source: LogSource,
	timestamp: string | null,
};

export type LogSource = "Docker" | "Laravel" | "Nginx" | "Supervisor";

export type ProjectConfig = {
	id: string,
	name: string,
	path: string,
	vite_auto: boolean,
};

export type ProjectStatus = { kind: "running" } | { kind: "partially_running" } | { kind: "unhealthy" } | { kind: "stopped" };

export type ProjectStatusEvent = {
	project_id: string,
	status: ProjectStatus,
};

export type ScaffoldChunk = {
	text: string,
	done: boolean,
	error: boolean,
};

export type ScaffoldTemplate = "Tall" | "InertiaVue3" | "InertiaReact" | "Filament" | "ApiOnly" | "Jetstream";

export type ServiceConfig = {
	image_tag: string,
	port: number,
};

export type ServiceId = "redis" | "postgres" | "mailpit" | "minio" | "soketi" | "meilisearch";

export type ServiceStatus = { kind: "stopped" } | { kind: "starting" } | { kind: "running" } | { kind: "stopping" } | { kind: "unhealthy" } | { kind: "error"; message: string };

export type SupervisorWorker = {
	name: string,
	status: string,
};

export type TemplateEntry = {
	id: string,
	name: string,
	description: string,
	tags: string[],
	compose_url: string,
};

export type VolumeInfo = {
	name: string,
	driver: string,
	mountpoint: string,
	/** Size in MB; null if Docker daemon has not computed usage data. */
	size_mb: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

