//! Select the supported Linux resolver backend from runtime and
//! `/etc/resolv.conf` evidence.
//!
//! Detection is conservative: `systemd-resolved` accepts its marker or runtime
//! directory, while `NetworkManager` requires its generated-file marker. Orcker
//! never edits `/etc/resolv.conf` directly.

/// Returns `true` if `systemd-resolved` appears to be in charge.
///
/// Inputs:
/// - `resolv_conf_text` - verbatim content of `/etc/resolv.conf`.
/// - `run_systemd_resolve_exists` - `std::fs::metadata("/run/systemd/resolve").is_ok()`.
///
/// Either piece of evidence is sufficient. A symlink to
/// `stub-resolv.conf` produces the marker comment Linux distros use, but
/// some systems run `systemd-resolved` without the stub link, so the
/// runtime-directory check covers them.
#[must_use]
pub fn detect_systemd_resolved(resolv_conf_text: &str, run_systemd_resolve_exists: bool) -> bool {
    if run_systemd_resolve_exists {
        return true;
    }
    resolv_conf_text
        .lines()
        .take(8)
        .any(|line| line.contains("systemd-resolved"))
}

/// Resolver managers Orcker knows how to configure on Linux.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LinuxResolverBackend {
    /// `systemd-resolved`, which is preferred when both managers are present.
    SystemdResolved,
    /// `NetworkManager` using its embedded dnsmasq plugin.
    NetworkManager,
    /// No safely configurable resolver manager was detected.
    Unsupported,
}

/// Select a Linux resolver backend. `systemd-resolved` may be identified by
/// runtime state or marker; `NetworkManager` requires its positive marker.
#[must_use]
pub fn detect_linux_backend(
    resolv_conf_text: &str,
    run_systemd_resolve_exists: bool,
) -> LinuxResolverBackend {
    if detect_systemd_resolved(resolv_conf_text, run_systemd_resolve_exists) {
        return LinuxResolverBackend::SystemdResolved;
    }
    if networkmanager_owns_resolv_conf(resolv_conf_text) {
        LinuxResolverBackend::NetworkManager
    } else {
        LinuxResolverBackend::Unsupported
    }
}

/// Whether `/etc/resolv.conf` positively identifies `NetworkManager` as its
/// generator. Merely running `NetworkManager` is intentionally insufficient.
#[must_use]
pub fn networkmanager_owns_resolv_conf(text: &str) -> bool {
    text.lines().take(8).any(|line| {
        line.to_ascii_lowercase()
            .contains("generated by networkmanager")
    })
}

/// Whether the reloaded resolver points at `NetworkManager`'s local dnsmasq
/// listener. This is the install post-condition; `nmcli` can exit successfully
/// even when its DNS plugin failed to start.
#[must_use]
pub fn networkmanager_dnsmasq_is_active(text: &str) -> bool {
    networkmanager_owns_resolv_conf(text)
        && text.lines().any(|line| {
            let mut fields = line.split_whitespace();
            fields.next() == Some("nameserver") && fields.next() == Some("127.0.0.1")
        })
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing
)]
mod tests {
    use super::*;

    #[test]
    fn runtime_dir_present_short_circuits_true() {
        assert!(detect_systemd_resolved("", true));
    }

    #[test]
    fn marker_in_first_lines_detects() {
        let text = "# This file is managed by man:systemd-resolved(8). Do not edit.\nnameserver 127.0.0.53\n";
        assert!(detect_systemd_resolved(text, false));
    }

    #[test]
    fn marker_buried_past_8_lines_is_not_detected() {
        let mut text = String::new();
        for _ in 0..8 {
            text.push_str("# filler\n");
        }
        text.push_str("# this file is managed by systemd-resolved\n");
        assert!(!detect_systemd_resolved(&text, false));
    }

    #[test]
    fn empty_text_and_no_runtime_dir_is_false() {
        assert!(!detect_systemd_resolved("", false));
    }

    #[test]
    fn plain_resolv_conf_without_marker_is_false() {
        let text = "nameserver 8.8.8.8\nnameserver 1.1.1.1\n";
        assert!(!detect_systemd_resolved(text, false));
    }

    #[test]
    fn backend_selection_prefers_resolved() {
        assert_eq!(
            detect_linux_backend("# Generated by NetworkManager", true),
            LinuxResolverBackend::SystemdResolved
        );
    }

    #[test]
    fn backend_selection_requires_networkmanager_marker() {
        assert_eq!(
            detect_linux_backend(
                "# Generated by NetworkManager\nnameserver 127.0.0.53",
                false
            ),
            LinuxResolverBackend::NetworkManager
        );
        assert_eq!(
            detect_linux_backend("nameserver 1.1.1.1", false),
            LinuxResolverBackend::Unsupported
        );
    }

    #[test]
    fn networkmanager_postcondition_requires_marker_and_loopback_nameserver() {
        assert!(networkmanager_dnsmasq_is_active(
            "# Generated by NetworkManager\nnameserver 127.0.0.1\n"
        ));
        assert!(!networkmanager_dnsmasq_is_active(
            "# Generated by NetworkManager\nnameserver 10.0.0.1\n"
        ));
        assert!(!networkmanager_dnsmasq_is_active("nameserver 127.0.0.1\n"));
    }
}
