//! Deterministic `docker-compose.yml` emission.

use crate::config::{DbEngine, Preset, StackConfig};
use crate::error::StackError;

/// Renders the project's `docker-compose.yml` as a string.
///
/// Output is deterministic: the same [`StackConfig`] always yields byte-identical
/// bytes, because the file is one fixed template with interpolated values rather
/// than a serialised map with an implementation-defined key order.
pub fn render_compose(cfg: &StackConfig) -> Result<String, StackError> {
    match cfg.preset() {
        Preset::Reference => Ok(render_reference(cfg)),
    }
}

/// Image tag the database service runs, per engine.
fn db_image(engine: DbEngine) -> &'static str {
    match engine {
        DbEngine::Postgres => "postgres:16-alpine",
    }
}

/// Readiness probe the database service runs, per engine.
///
/// `$$` is compose's escape for a literal `$`: the credentials come from the
/// project's `env_file` and are expanded by the shell inside the container. A
/// single `$` would make compose substitute at parse time, which both warns and
/// resolves to an empty string on the host.
fn db_healthcheck_probe(engine: DbEngine) -> &'static str {
    match engine {
        DbEngine::Postgres => "pg_isready -U $${DB_USERNAME} -d $${DB_DATABASE}",
    }
}

/// The full production-parity topology: app + nginx + database, dual networks,
/// every published port bound to the loopback interface.
fn render_reference(cfg: &StackConfig) -> String {
    let site = cfg.site().as_str();
    let php = cfg.php().as_str();
    let uid = cfg.uid();
    let gid = cfg.gid();
    let http_port = cfg.ports().http_loopback();
    let vite_port = cfg.ports().vite();
    let image = db_image(cfg.db());
    let probe = db_healthcheck_probe(cfg.db());

    format!(
        r#"# Generated by orcker.
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      args:
        PHP_VERSION: "{php}"
        UID: "{uid}"
        GID: "{gid}"
    restart: "no"
    volumes:
      - ./:/var/www
    ports:
      - "127.0.0.1:{vite_port}:5173"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - {site}
      - development
  nginx:
    image: nginx:1.27-alpine
    restart: "no"
    environment:
      FASTCGI_PASS: "app:9000"
    volumes:
      - ./public:/var/www/public
      - ./storage/app/public:/var/www/storage/app/public:ro
    ports:
      - "127.0.0.1:{http_port}:80"
    depends_on:
      - app
    networks:
      - {site}
      - development
  db:
    image: {image}
    restart: "no"
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "{probe}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - {site}-db-data:/var/lib/postgresql/data
    networks:
      - {site}
volumes:
  {site}-db-data:
networks:
  {site}:
    driver: bridge
  development:
    external: true
"#
    )
}
